#
## Copyright (C) 2019 Wind River Systems, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

PREFERRED_VERSION_ceph = "13.2.2"
PREFERRED_VERSION_dnsmasq = "2.76"
PREFERRED_VERSION_keyutils = "1.6"
PREFERRED_VERSION_python-voluptuous = "0.8.9"
PREFERRED_VERSION_python3-cherrypy = "18.2.0"
PREFERRED_VERSION_python-cheroot = "7.0.0"
PREFERRED_VERSION_python3-cheroot = "7.0.0"
PREFERRED_VERSION_python-cherrypy = "git"
PREFERRED_VERSION_pythonkeystoneauth1 = "3.17.1"
PREFERRED_VERSION_drbd-utils = "8.4.3rc1"
PREFERRED_VERSION_python-pyyaml = "3.13"
PREFERRED_VERSION_python-cmd2 = "0.6.8"
PREFERRED_VERSION_python-expect = "4.6.0"
PREFERRED_VERSION_python-pika = "0.10.0%"
PREFERRED_VERSION_python-keyring = "5.3"
PREFERRED_VERSION_python-barbican = "8.0.%"
PREFERRED_VERSION_python-keystone = "15.0.%"
PREFERRED_VERSION_python-flask = "1.0.2"
PREFERRED_VERSION_python-keystonemiddleware = "5.1.%"
PREFERRED_VERSION_python-oslo.cache= "1.26.%"
PREFERRED_VERSION_python-oslo.concurrency= "3.26.%"
PREFERRED_VERSION_python-oslo.log= "3.38.%"
PREFERRED_VERSION_python-oslo.middleware = "3.31.%"
PREFERRED_VERSION_python-oslo.serialization = "2.23.%"
PREFERRED_VERSION_python-oslo.policy = "1.43.%"
PREFERRED_VERSION_python-pysaml2 = "4.5.%"
PREFERRED_VERSION_python-sqlalchemy = "1.1.17"
PREFERRED_VERSION_python-werkzeug = "0.14.%"
PREFERRED_VERSION_python-neutronclient = "6.12.%"
PREFERRED_VERSION_python-oslo.i18n = "3.20.%"
PREFERRED_VERSION_python-iso8601 = "0.1.12"
PREFERRED_VERSION_python-six = "1.11.%"
PREFERRED_VERSION_python-docker = "3.3.0"
PREFERRED_VERSION_python-pyudev = "0.16.1"
PREFERRED_VERSION_python-django = "1.11.20+%"
PREFERRED_VERSION_python-django-babel = "0.6.2+%"
PREFERRED_VERSION_python-pysnmp = "4.2.5"
PREFERRED_VERSION_python-dateutil = "2.8.1"
PREFERRED_VERSION_python-adal = "1.0.2"
PREFERRED_VERSION_python-osprofiler = "2.3.0+%"
PREFERRED_VERSION_python-amqp = "2.5.2"
PREFERRED_VERSION_python-ryu = "4.24+%"
PREFERRED_VERSION_docker-distribution = "v2.6.2"
PREFERRED_VERSION_kuberenetes = "1.16.%"
PREFERRED_VERSION_ruby = "2.0.0-p648"
PREFERRED_VERSION_ruby-native = "2.0.0-p648"
PREFERRED_VERSION_puppet = "4.8.2"
PREFERRED_VERSION_python-eventlet = "0.18.4"
PREFERRED_VERSION_lldpd = "0.9.0"
